apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: catalog
        image: doracr.azurecr.io/grafana/grafana
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: acr-secret
